[package]
name = "cxxrustdemo"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["staticlib"]
# change to cdylib if you want to produce just a .wasm file from the rust.
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../wasm-bindgen" }
