[build]
target = "wasm32-unknown-emscripten"
rustflags = [
    "-Clink-args=--no-entry",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
     "-C",
    "panic=abort",
    "-Clink-args=-sDISABLE_EXCEPTION_CATCHING=1",
    "-C",
    "relocation-model=static",
]

